services:
  weaviate:
    image: semitechnologies/weaviate:1.22.3
    restart: always
    ports:
      - "8081:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai'
      TEXT2VEC_OPENAI_APIKEY: ${OPENAI_API_KEY}
      WEAVIATE_CLUSTER: 'false'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
